## Week 02 Question Set

a)  **What do you feel was the most impressive thing you did in class last week was?**
Learn how to connect my work in R to github. Small step for most, but I thought it was really neat to finally make it happen! (Perhaps I said this prematurely since I didn't push the correct version of my homework)

b)  **What is your weekly goal for making progress on your project? What is the next step?**
Laura sent me the snow crab data and some notes, so I would like to look through the contents to get an idea of what I am working with. 

c)  **There were two readings this week not from the textbook, meant for two different audiences. Which reading did you get the most out of and why? Do you have any questions regarding the Journal of Shellfish Research paper?**
I really enjoyed the Journal of Shellfish paper because it was directed towards people with a working understanding of genomics who are interested in entering the world of computational analysis (which is precisely the spot that I am in). 


d)  **What is your favorite thing about markdown and why?**
I like that markdown is versatile; it can be used for many programming languages and formatted using  reproducible syntax.

e) **What is the difference between `curl` and `wget`? When would you used one over the other?**
I'm still learning the extent of what each can do--I think I need to play with them in different ways to really understand what each one does. From what I know now, it seems like that "curl" transfers data to or from a server whereas "wget" can only download files.  

