---
title: "blast"
output: html_document
date: "2023-03-30"
---

#Download Software


Will need this later on..

```{r}
library(tidyverse)
```





Getting BLAST

```{bash}
mkdir /home/jovyan/applications
cd /home/jovyan/applications
curl -O https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.13.0+-x64-linux.tar.gz
```


unzipping..


```{bash}
#unzip the file
cd /home/jovyan/applications
tar -xf ncbi-blast-2.13.0+-x64-linux.tar.gz
```


Lets see if blast works!

```{bash}
~/applications/ncbi-blast-2.13.0+/bin/blastx -h
```


Need to get uniprot swiss-prot fasta to make database.

```{bash}
cd ../data
curl -O https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
mv uniprot_sprot.fasta.gz uniprot_sprot_r2023_01.fasta.gz
gunzip -k uniprot_sprot_r2023_01.fasta.gz

```


Did that work? 
```{bash}
ls ../data
```


# Making a blast database

```{bash}
~/applications/ncbi-blast-2.13.0+/bin/makeblastdb \
-in ../data/uniprot_sprot_r2023_01.fasta \
-dbtype prot \
-out ../blastdb/uniprot_sprot_r2023_01
```


# Getting an unknown Query

```{bash}
curl https://eagle.fish.washington.edu/cnidarian/Ab_4denovo_CLC6_a.fa \
-k \
> ../data/Ab_4denovo_CLC6_a.fa
```



Checking it out 

```{bash}
head ../data/Ab_4denovo_CLC6_a.fa
echo "How many sequences are there?"
grep -c ">" ../data/Ab_4denovo_CLC6_a.fa
```


# Running Blastx

```{bash}
~/applications/ncbi-blast-2.13.0+/bin/blastx \
-query ../data/Ab_4denovo_CLC6_a.fa \
-db ../blastdb/uniprot_sprot_r2023_01 \
-out ../output/Ab_4-uniprot_blastx.tab \
-evalue 1E-20 \
-num_threads 20 \
-max_target_seqs 1 \
-outfmt 6
```






```{bash}
head -2 ../output/Ab_4-uniprot_blastx.tab
wc -l ../output/Ab_4-uniprot_blastx.tab
```

```{bash}
curl -O -H "Accept: text/plain; format=tsv" "https://gannet.fish.washington.edu/seashell/snaps/uniprot_table_r2023_01.tab"
```
```{bash}
head -2 ../output/Ab_4-uniprot_blastx.tab
wc -l ../output/Ab_4-uniprot_blastx.tab
```
#I am stuck here... keep getting an error (tr: write error: Broken pipe)
```{bash}
tr '|' '\t' < ../output/Ab_4-uniprot_blastx.tab | head -2
```
#the chunk below won't run (doesn't even show errors--it just buffers breifly)
```{bash}
tr '|' '\t' < ../output/Ab_4-uniprot_blastx.tab \
> ../output/Ab_4-uniprot_blastx_sep.tab
```

#this chunk works but is not consistent with the assignemnet instructions (it uses a .fasta file instead 
# of a .tab)
```{bash}
head -2 ../data/uniprot_sprot_r2023_01.fasta
wc -l ../data/uniprot_sprot_r2023_01.fasta
```

#this says that in file(file, "rt") that it cannot open this file (no file/directory)
#not sure why it says this becuase this exact file is in my output folder
bltabl <- read.csv("../output/Ab_4-uniprot_blastx_sep.tab", sep = '\t', header = FALSE)

#same error message as above 
spgo <- read.csv("../data/uniprot_sprot_r2023_01.fasta", sep = '\t', header = TRUE)

str(spgo)

