---
title: "07-CGmotifs"
author: "Courtney Skalley"
date: "2023-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash}
cd ../data
curl -O https://owl.fish.washington.edu/halfshell/genomic-databank/cbai_genome_v1.01.fasta 
ls ../data
```


```{r}
library(seqinr)

input_file <- "../data/cbai_genome_v1.01.fasta"
sequences <- read.fasta(input_file)
```


```{r}
# Set the seed for reproducibility (optional)
set.seed(42)

number_of_sequences_to_select <- 10

if (length(sequences) < number_of_sequences_to_select) {
  warning("There are fewer than 10 sequences in the fasta file. All sequences will be selected.")
  number_of_sequences_to_select <- length(sequences)
}

selected_indices <- sample(length(sequences), number_of_sequences_to_select)
selected_sequences <- sequences[selected_indices]
```

```{r}
# Replace 'output.fasta' with your desired output file name
output_file <- "../output/07-output.fa"
write.fasta(selected_sequences, names(selected_sequences), output_file, open = "w")
```


```{bash}
# download index file
cd ../data
curl -O https://owl.fish.washington.edu/halfshell/genomic-databank/cbai_genome_v1.01.fasta.fai
ls ../data
```

```{bash}
#needed downstream for IGV
/home/shared/samtools-1.12/samtools faidx \
../output/07-output.fa
```

```{bash}
fuzznuc -sequence ../output/07-output.fa -pattern CG -rformat gff -outfile ../output/CGoutput.gff
```

